[package]
name = "blog-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.2", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
actix-web = "4.8.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
json = "0.12.4"
tera = "1.20.0"